import {
  LeadStatus,
  OrderStatus,
  QuoteStatus,
  SampleStatus,
  SampleCreditStatus,
  InventoryMovementType,
  CustomerType,
  SalesChannel,
  PaymentStatus,
  ProductionBatchStatus,
  QCStatus,
  ShipmentStatus,
  NotificationType,
  ActivityActionType,
} from '../types/schema';

// ================= 1. MASTER PRODUCTS & VARIANTS =================
export const INITIAL_PRODUCTS = [
  {
    id: 'prod-001',
    title: 'AST Handmade Macramé Belt',
    handle: 'ast-handmade-macrame-belt',
    category: 'Belts & Accessories',
    status: 'Active',
    description: 'Fully handmade, very strong, and comfortable to wear. Crafted from 100% premium hand-dyed organic cotton cords with vintage brushed alloy hardware.',
    material: '100% Organic Cotton Cord (4.5mm)',
    buckleMaterial: 'Vintage Brushed Alloy (Anti-Rust / Lead-Free)',
    dimensions: '1.4" Width (3.5 cm) • 43" Length (109 cm) stretch-flexible',
    moq: 100,
    unitCost: 400, // COGS breakdown: cord 180 + buckle 70 + artisan wage 120 + box 30
    retailPrice: 850,
    retailRegularPrice: 1050,
    wholesaleTier1Price: 720, // 100-299
    wholesaleTier2Price: 650, // 300-499
    wholesaleTier3Price: 580, // 500-999
    wholesaleTier4Price: 520, // 1000+
    productionLeadTime: '15–20 Business Days',
    featuredImage: '/src/assets/products/Black/1.webp',
    variants: [
      {
        id: 'var-blk-m',
        sku: 'AST-BLT-BLK-M',
        color: 'Black',
        hex: '#18181B',
        size: 'M (32–35")',
        retailPrice: 850,
        wholesalePrice: 650,
        unitCost: 400,
        barcode: '8801940001',
        stock: { onHand: 65, reserved: 15, available: 50, lowStockThreshold: 20 },
      },
      {
        id: 'var-blk-l',
        sku: 'AST-BLT-BLK-L',
        color: 'Black',
        hex: '#18181B',
        size: 'L (35–38")',
        retailPrice: 850,
        wholesalePrice: 650,
        unitCost: 400,
        barcode: '8801940002',
        stock: { onHand: 50, reserved: 10, available: 40, lowStockThreshold: 20 },
      },
      {
        id: 'var-nvy-m',
        sku: 'AST-BLT-NVY-M',
        color: 'Navy',
        hex: '#1C2841',
        size: 'M (32–35")',
        retailPrice: 850,
        wholesalePrice: 650,
        unitCost: 400,
        barcode: '8801940003',
        stock: { onHand: 45, reserved: 5, available: 40, lowStockThreshold: 15 },
      },
      {
        id: 'var-nvy-l',
        sku: 'AST-BLT-NVY-L',
        color: 'Navy',
        hex: '#1C2841',
        size: 'L (35–38")',
        retailPrice: 850,
        wholesalePrice: 650,
        unitCost: 400,
        barcode: '8801940004',
        stock: { onHand: 35, reserved: 5, available: 30, lowStockThreshold: 15 },
      },
      {
        id: 'var-brn-m',
        sku: 'AST-BLT-BRN-M',
        color: 'Brown',
        hex: '#5C4033',
        size: 'M (32–35")',
        retailPrice: 850,
        wholesalePrice: 650,
        unitCost: 400,
        barcode: '8801940005',
        stock: { onHand: 40, reserved: 10, available: 30, lowStockThreshold: 15 },
      },
      {
        id: 'var-brn-l',
        sku: 'AST-BLT-BRN-L',
        color: 'Brown',
        hex: '#5C4033',
        size: 'L (35–38")',
        retailPrice: 850,
        wholesalePrice: 650,
        unitCost: 400,
        barcode: '8801940006',
        stock: { onHand: 30, reserved: 5, available: 25, lowStockThreshold: 15 },
      },
      {
        id: 'var-mrn-m',
        sku: 'AST-BLT-MRN-M',
        color: 'Maroon',
        hex: '#800000',
        size: 'M (32–35")',
        retailPrice: 850,
        wholesalePrice: 650,
        unitCost: 400,
        barcode: '8801940007',
        stock: { onHand: 22, reserved: 10, available: 12, lowStockThreshold: 15 },
      },
      {
        id: 'var-mrn-l',
        sku: 'AST-BLT-MRN-L',
        color: 'Maroon',
        hex: '#800000',
        size: 'L (35–38")',
        retailPrice: 850,
        wholesalePrice: 650,
        unitCost: 400,
        barcode: '8801940008',
        stock: { onHand: 18, reserved: 2, available: 16, lowStockThreshold: 10 },
      },
      {
        id: 'var-khk-m',
        sku: 'AST-BLT-KHK-M',
        color: 'Khaki',
        hex: '#C3B091',
        size: 'M (32–35")',
        retailPrice: 850,
        wholesalePrice: 650,
        unitCost: 400,
        barcode: '8801940009',
        stock: { onHand: 55, reserved: 15, available: 40, lowStockThreshold: 20 },
      },
      {
        id: 'var-khk-l',
        sku: 'AST-BLT-KHK-L',
        color: 'Khaki',
        hex: '#C3B091',
        size: 'L (35–38")',
        retailPrice: 850,
        wholesalePrice: 650,
        unitCost: 400,
        barcode: '8801940010',
        stock: { onHand: 40, reserved: 10, available: 30, lowStockThreshold: 20 },
      },
    ],
  },
];

// ================= 2. WHOLESALE COMPANIES =================
export const INITIAL_COMPANIES = [
  {
    id: 'comp-001',
    name: 'Atelier Artisan S.A.',
    country: 'France',
    city: 'Paris',
    address: '14 Rue du Faubourg Saint-Honoré',
    taxId: 'FR849201934',
    tier: 'Tier 02 (Brand Collection)',
    status: 'Active',
    paymentTerms: '50% Deposit, 50% Before Shipping',
    creditLimit: 15000,
    totalSpent: 272600,
    contacts: [
      {
        id: 'cont-001',
        name: 'Camille Laurent',
        role: 'Head of Sourcing & Merchandising',
        email: 'camille@atelierartisan.fr',
        phone: '+33 6 42 90 11 22',
        whatsapp: '+33642901122',
        isPrimary: true,
      },
      {
        id: 'cont-002',
        name: 'Jean-Paul Mercier',
        role: 'Supply Chain Director',
        email: 'jp.mercier@atelierartisan.fr',
        phone: '+33 6 42 90 11 25',
        whatsapp: '+33642901125',
        isPrimary: false,
      },
    ],
  },
  {
    id: 'comp-002',
    name: 'Nordic Bohemian Living Ltd',
    country: 'Denmark',
    city: 'Copenhagen',
    address: 'Vesterbrogade 48, 1620 København',
    taxId: 'DK99281726',
    tier: 'Tier 01 (Boutique Run)',
    status: 'Active',
    paymentTerms: '100% Advance on Samples / 50-50 Bulk',
    creditLimit: 8000,
    totalSpent: 4400,
    contacts: [
      {
        id: 'cont-003',
        name: 'Freja Lindegaard',
        role: 'Creative Director',
        email: 'freja@nordicbohemian.dk',
        phone: '+45 20 89 44 11',
        whatsapp: '+4520894411',
        isPrimary: true,
      },
    ],
  },
  {
    id: 'comp-003',
    name: 'Sonoma Coast Apparel Co.',
    country: 'United States',
    city: 'San Francisco, CA',
    address: '420 Montgomery St, Suite 1200',
    taxId: 'US-CA-9482910',
    tier: 'Tier 03 (Global Retailer)',
    status: 'Prospect / Lead',
    paymentTerms: 'Net 30',
    creditLimit: 35000,
    totalSpent: 3900,
    contacts: [
      {
        id: 'cont-004',
        name: 'Marcus Vance',
        role: 'VP Product Development',
        email: 'm.vance@sonomacoast.com',
        phone: '+1 415 890 2200',
        whatsapp: '+14158902200',
        isPrimary: true,
      },
      {
        id: 'cont-005',
        name: 'Elena Rostova',
        role: 'Sourcing Specialist',
        email: 'elena@sonomacoast.com',
        phone: '+1 415 890 2205',
        whatsapp: '+14158902205',
        isPrimary: false,
      },
    ],
  },
];

// ================= 3. RETAIL CUSTOMERS =================
export const INITIAL_CUSTOMERS = [
  {
    id: 'cust-ret-001',
    name: 'Tanvir Hossain',
    email: 'tanvir.h@gmail.com',
    phone: '+880 1711-234567',
    type: CustomerType.RETAIL,
    district: 'Dhaka (Gulshan)',
    address: 'House 42, Road 11, Block D, Gulshan-1',
    totalSpent: 1590,
    ordersCount: 1,
    createdAt: '2026-08-15',
  },
  {
    id: 'cust-ret-002',
    name: 'Nusrat Jahan',
    email: 'nusrat.jahan@yahoo.com',
    phone: '+880 1819-876543',
    type: CustomerType.RETAIL,
    district: 'Chittagong',
    address: 'Amanat Tower, 4th Floor, Nasirabad',
    totalSpent: 950,
    ordersCount: 1,
    createdAt: '2026-08-28',
  },
];

// ================= 4. WHOLESALE CRM LEADS =================
export const INITIAL_LEADS = [
  {
    id: 'lead-001',
    title: 'Sonoma Coast Summer 2027 Line',
    companyId: 'comp-003',
    companyName: 'Sonoma Coast Apparel Co.',
    contactName: 'Marcus Vance',
    contactEmail: 'm.vance@sonomacoast.com',
    contactPhone: '+1 415 890 2200',
    country: 'United States',
    channel: SalesChannel.WHOLESALE,
    status: LeadStatus.SAMPLE_SENT,
    estimatedPieces: 500,
    estimatedValueBDT: 290000,
    currency: 'USD',
    assignedTo: 'Admin',
    notes: 'Requested paid sample batch in Black & Khaki. Target launch Summer 2027.',
    createdAt: '2026-08-20',
    updatedAt: '2026-09-02',
  },
  {
    id: 'lead-002',
    title: 'Boutique Hotel Gift Shop Project',
    companyId: 'comp-002',
    companyName: 'Nordic Bohemian Living Ltd',
    contactName: 'Freja Lindegaard',
    contactEmail: 'freja@nordicbohemian.dk',
    contactPhone: '+45 20 89 44 11',
    country: 'Denmark',
    channel: SalesChannel.WHOLESALE,
    status: LeadStatus.QUOTE_SENT,
    estimatedPieces: 250,
    estimatedValueBDT: 162500,
    currency: 'EUR',
    assignedTo: 'Admin',
    notes: 'Quotation QTE-2026-002 sent with sample credit applied. Awaiting final board sign-off.',
    createdAt: '2026-08-25',
    updatedAt: '2026-09-05',
  },
  {
    id: 'lead-003',
    title: 'Autumn 2026 Re-order Expansion',
    companyId: 'comp-001',
    companyName: 'Atelier Artisan S.A.',
    contactName: 'Camille Laurent',
    contactEmail: 'camille@atelierartisan.fr',
    contactPhone: '+33 6 42 90 11 22',
    country: 'France',
    channel: SalesChannel.WHOLESALE,
    status: LeadStatus.WON,
    estimatedPieces: 400,
    estimatedValueBDT: 260000,
    currency: 'EUR',
    assignedTo: 'Admin',
    notes: 'Quote accepted and wholesale PO issued (ORD-WHL-2026-001).',
    createdAt: '2026-08-10',
    updatedAt: '2026-09-01',
  },
];

// ================= 5. PAID SAMPLE ORDERS & CREDIT LIFECYCLE =================
export const INITIAL_SAMPLES = [
  {
    id: 'sam-001',
    sampleNumber: 'SAM-2026-001',
    companyId: 'comp-001',
    companyName: 'Atelier Artisan S.A.',
    contactName: 'Camille Laurent',
    contactEmail: 'camille@atelierartisan.fr',
    contactPhone: '+33 6 42 90 11 22',
    shippingAddress: '14 Rue du Faubourg Saint-Honoré, 75008 Paris, France',
    items: [
      { variantId: 'var-blk-m', color: 'Black', size: 'M (32–35")', quantity: 1, samplePrice: 1200 },
      { variantId: 'var-brn-m', color: 'Brown', size: 'M (32–35")', quantity: 1, samplePrice: 1200 },
    ],
    sampleTotalBDT: 2400,
    shippingFeeBDT: 2500,
    totalPaidBDT: 4900,
    status: SampleStatus.DELIVERED,
    trackingNumber: 'DHL-EX-88291039',
    courier: 'DHL Express',
    paymentStatus: PaymentStatus.PAID,
    paidAt: '2026-08-12',
    deliveredAt: '2026-08-18',
    sampleCreditEligible: true,
    sampleCreditAmountBDT: 2400,
    creditStatus: SampleCreditStatus.REDEEMED,
    appliedToOrderId: 'ord-whl-001',
    redeemedAt: '2026-09-01',
    notes: 'Sample verified in Paris workshop. ৳2,400 credit deducted from Invoice ORD-WHL-2026-001.',
  },
  {
    id: 'sam-002',
    sampleNumber: 'SAM-2026-002',
    companyId: 'comp-002',
    companyName: 'Nordic Bohemian Living Ltd',
    contactName: 'Freja Lindegaard',
    contactEmail: 'freja@nordicbohemian.dk',
    contactPhone: '+45 20 89 44 11',
    shippingAddress: 'Vesterbrogade 48, 1620 København, Denmark',
    items: [
      { variantId: 'var-khk-m', color: 'Khaki', size: 'M (32–35")', quantity: 1, samplePrice: 1200 },
      { variantId: 'var-nvy-m', color: 'Navy', size: 'M (32–35")', quantity: 1, samplePrice: 1200 },
    ],
    sampleTotalBDT: 2400,
    shippingFeeBDT: 2000,
    totalPaidBDT: 4400,
    status: SampleStatus.DELIVERED,
    trackingNumber: 'FEDEX-IN-9920194',
    courier: 'FedEx Priority',
    paymentStatus: PaymentStatus.PAID,
    paidAt: '2026-08-26',
    deliveredAt: '2026-09-01',
    sampleCreditEligible: true,
    sampleCreditAmountBDT: 2400,
    creditStatus: SampleCreditStatus.AVAILABLE,
    appliedToOrderId: null,
    notes: 'Delivered. Credit of ৳2,400 ready to apply when Freja confirms QTE-2026-002.',
  },
  {
    id: 'sam-003',
    sampleNumber: 'SAM-2026-003',
    companyId: 'comp-003',
    companyName: 'Sonoma Coast Apparel Co.',
    contactName: 'Marcus Vance',
    contactEmail: 'm.vance@sonomacoast.com',
    contactPhone: '+1 415 890 2200',
    shippingAddress: '420 Montgomery St, Suite 1200, San Francisco, CA 94104',
    items: [
      { variantId: 'var-blk-m', color: 'Black', size: 'M (32–35")', quantity: 1, samplePrice: 1200 },
      { variantId: 'var-khk-l', color: 'Khaki', size: 'L (35–38")', quantity: 1, samplePrice: 1200 },
    ],
    sampleTotalBDT: 2400,
    shippingFeeBDT: 1500,
    totalPaidBDT: 3900,
    status: SampleStatus.SHIPPED,
    trackingNumber: 'DHL-US-44920194',
    courier: 'DHL Express',
    paymentStatus: PaymentStatus.PAID,
    paidAt: '2026-08-30',
    sampleCreditEligible: true,
    sampleCreditAmountBDT: 2400,
    creditStatus: SampleCreditStatus.AVAILABLE,
    notes: 'In transit to San Francisco. Est delivery Sept 8.',
  },
];

// ================= 6. B2B QUOTATIONS =================
export const INITIAL_QUOTES = [
  {
    id: 'quote-001',
    quoteNumber: 'QTE-2026-001',
    companyId: 'comp-001',
    companyName: 'Atelier Artisan S.A.',
    contactName: 'Camille Laurent',
    contactEmail: 'camille@atelierartisan.fr',
    contactPhone: '+33 6 42 90 11 22',
    status: QuoteStatus.ACCEPTED,
    currency: 'BDT',
    validUntil: '2026-09-30',
    moq: 300,
    items: [
      { variantId: 'var-blk-m', title: 'Black [M]', color: 'Black', size: 'M', quantity: 100, unitPrice: 650, total: 65000 },
      { variantId: 'var-blk-l', title: 'Black [L]', color: 'Black', size: 'L', quantity: 100, unitPrice: 650, total: 65000 },
      { variantId: 'var-brn-m', title: 'Brown [M]', color: 'Brown', size: 'M', quantity: 100, unitPrice: 650, total: 65000 },
      { variantId: 'var-khk-m', title: 'Khaki [M]', color: 'Khaki', size: 'M', quantity: 100, unitPrice: 650, total: 65000 },
    ],
    subtotalBDT: 260000,
    sampleCreditDeductionBDT: 2400,
    shippingBDT: 15000,
    totalBDT: 272600,
    paymentTerms: '50% Production Advance, 50% Balance on Air Cargo Dispatch',
    notes: 'Custom branded kraft tag packaging included. 100% sample credit applied.',
    createdAt: '2026-08-22',
  },
  {
    id: 'quote-002',
    quoteNumber: 'QTE-2026-002',
    companyId: 'comp-002',
    companyName: 'Nordic Bohemian Living Ltd',
    contactName: 'Freja Lindegaard',
    contactEmail: 'freja@nordicbohemian.dk',
    contactPhone: '+45 20 89 44 11',
    status: QuoteStatus.SENT,
    currency: 'BDT',
    validUntil: '2026-09-25',
    moq: 200,
    items: [
      { variantId: 'var-khk-m', title: 'Khaki [M]', color: 'Khaki', size: 'M', quantity: 100, unitPrice: 650, total: 65000 },
      { variantId: 'var-nvy-m', title: 'Navy [M]', color: 'Navy', size: 'M', quantity: 100, unitPrice: 650, total: 65000 },
      { variantId: 'var-brn-m', title: 'Brown [M]', color: 'Brown', size: 'M', quantity: 50, unitPrice: 650, total: 32500 },
    ],
    subtotalBDT: 162500,
    sampleCreditDeductionBDT: 2400,
    shippingBDT: 12000,
    totalBDT: 172100,
    paymentTerms: '50% Advance, 50% on Bill of Lading',
    notes: 'Special Nordic boutique trial volume discount.',
    createdAt: '2026-09-02',
  },
];

// ================= 7. UNIFIED ORDERS =================
export const INITIAL_ORDERS = [
  {
    id: 'ord-whl-001',
    orderNumber: 'ORD-WHL-2026-001',
    channel: SalesChannel.WHOLESALE,
    companyId: 'comp-001',
    companyName: 'Atelier Artisan S.A.',
    contactName: 'Camille Laurent',
    name: 'Camille Laurent',
    phone: '+33 6 42 90 11 22',
    email: 'camille@atelierartisan.fr',
    address: '14 Rue du Faubourg Saint-Honoré, 75008 Paris, France',
    city: 'Paris',
    country: 'France',
    status: OrderStatus.PRODUCTION,
    paymentStatus: PaymentStatus.PARTIAL,
    paymentTerms: '50% Deposit Paid (৳136,300), 50% Balance Due (৳136,300)',
    depositPaid: 136300,
    balanceDue: 136300,
    fulfillmentStatus: 'In Production',
    items: [
      { variantId: 'var-blk-m', name: 'Macramé Belt', color: 'Black', size: 'M (32–35")', quantity: 100, unitPrice: 650, unitCost: 400, total: 65000 },
      { variantId: 'var-blk-l', name: 'Macramé Belt', color: 'Black', size: 'L (35–38")', quantity: 100, unitPrice: 650, unitCost: 400, total: 65000 },
      { variantId: 'var-brn-m', name: 'Macramé Belt', color: 'Brown', size: 'M (32–35")', quantity: 100, unitPrice: 650, unitCost: 400, total: 65000 },
      { variantId: 'var-khk-m', name: 'Macramé Belt', color: 'Khaki', size: 'M (32–35")', quantity: 100, unitPrice: 650, unitCost: 400, total: 65000 },
    ],
    subtotal: 260000,
    sampleCreditApplied: 2400,
    shippingCost: 15000,
    grandTotal: 272600,
    totalCost: 272600,
    currency: 'BDT',
    inventoryReserved: true,
    productionBatchId: 'BAT-2026-081',
    timeline: [
      { time: '2026-09-01 10:15', text: 'Quotation QTE-2026-001 approved by Camille Laurent. Wholesale order created.' },
      { time: '2026-09-01 10:20', text: 'Sample Credit of ৳2,400 (SAM-2026-001) successfully applied to invoice.' },
      { time: '2026-09-01 14:00', text: '50% Wire Transfer deposit of ৳136,300 verified via City Bank PLC.' },
      { time: '2026-09-02 09:00', text: 'Production batch BAT-2026-081 queued for Savar Artisan Workshop.' },
    ],
    note: 'Custom Atelier Noir woven care labels attached to buckle loops.',
    createdAt: '2026-09-01',
  },
  {
    id: 'ord-ret-001',
    orderNumber: 'ORD-RET-2026-8812',
    channel: SalesChannel.RETAIL,
    name: 'Tanvir Hossain',
    contactName: 'Tanvir Hossain',
    phone: '+880 1711-234567',
    email: 'tanvir.h@gmail.com',
    address: 'House 42, Road 11, Block D, Gulshan-1, Dhaka',
    city: 'Dhaka',
    country: 'Bangladesh',
    status: OrderStatus.CONFIRMED,
    paymentStatus: PaymentStatus.PENDING,
    paymentTerms: 'Cash On Delivery (COD)',
    depositPaid: 0,
    balanceDue: 1590,
    fulfillmentStatus: 'Ready to Ship',
    items: [
      { variantId: 'var-blk-m', name: 'Macramé Belt', color: 'Black', size: 'M (32–35")', quantity: 1, unitPrice: 850, unitCost: 400, total: 850 },
      { variantId: 'var-khk-m', name: 'Macramé Belt', color: 'Khaki', size: 'M (32–35")', quantity: 1, unitPrice: 640, unitCost: 400, total: 640 },
    ],
    subtotal: 1490,
    sampleCreditApplied: 0,
    shippingCost: 100,
    grandTotal: 1590,
    totalCost: 1590,
    currency: 'BDT',
    inventoryReserved: true,
    timeline: [
      { time: '2026-09-06 14:22', text: 'Order placed via Facebook Ad Retail landing page.' },
      { time: '2026-09-06 15:00', text: 'Customer confirmed phone call verification. Inventory reserved (1x Black M, 1x Khaki M).' },
    ],
    note: 'Call before delivery.',
    createdAt: '2026-09-06',
  },
  {
    id: 'ord-ret-002',
    orderNumber: 'ORD-RET-2026-8815',
    channel: SalesChannel.RETAIL,
    name: 'Nusrat Jahan',
    contactName: 'Nusrat Jahan',
    phone: '+880 1819-876543',
    email: 'nusrat.jahan@yahoo.com',
    address: 'Amanat Tower, 4th Floor, Nasirabad, Chittagong',
    city: 'Chittagong',
    country: 'Bangladesh',
    status: OrderStatus.SHIPPED,
    paymentStatus: PaymentStatus.PENDING,
    paymentTerms: 'Cash On Delivery (COD)',
    depositPaid: 0,
    balanceDue: 950,
    fulfillmentStatus: 'In Transit',
    courier: 'Steadfast Courier',
    trackingNumber: 'ST-99820194BD',
    items: [
      { variantId: 'var-brn-m', name: 'Macramé Belt', color: 'Brown', size: 'M (32–35")', quantity: 1, unitPrice: 850, unitCost: 400, total: 850 },
    ],
    subtotal: 850,
    sampleCreditApplied: 0,
    shippingCost: 100,
    grandTotal: 950,
    totalCost: 950,
    currency: 'BDT',
    inventoryReserved: false,
    timeline: [
      { time: '2026-09-05 11:10', text: 'Order placed online.' },
      { time: '2026-09-05 16:30', text: 'Dispatched with Steadfast Courier (ST-99820194BD). Inventory deducted.' },
    ],
    note: 'Leave parcel at front desk if unavailable.',
    createdAt: '2026-09-05',
  },
];

// ================= 8. PRODUCTION & QC BATCHES =================
export const INITIAL_BATCHES = [
  {
    id: 'BAT-2026-081',
    batchNumber: 'BAT-2026-081',
    orderId: 'ord-whl-001',
    orderNumber: 'ORD-WHL-2026-001',
    productId: 'prod-001',
    productTitle: 'AST Handmade Macramé Belt',
    variantId: 'var-blk-m',
    sku: 'AST-BLT-BLK-M',
    color: 'Black',
    size: 'M (32–35")',
    quantity: 100,
    completedQty: 100,
    status: ProductionBatchStatus.QUALITY_CONTROL,
    assignedWorkshop: 'Artisan Workshop 1 (Savar)',
    assignedTeam: 'Master Weaver Rafiq',
    startDate: '2026-09-02',
    expectedCompletion: '2026-09-12',
    actualCompletion: '2026-09-06',
    notes: 'Order for Atelier Artisan Paris. High tension braid specifications.',
    qcStatus: QCStatus.PENDING,
    qcInspections: [],
  },
  {
    id: 'BAT-2026-082',
    batchNumber: 'BAT-2026-082',
    orderId: 'ord-whl-001',
    orderNumber: 'ORD-WHL-2026-001',
    productId: 'prod-001',
    productTitle: 'AST Handmade Macramé Belt',
    variantId: 'var-blk-l',
    sku: 'AST-BLT-BLK-L',
    color: 'Black',
    size: 'L (35–38")',
    quantity: 100,
    completedQty: 60,
    status: ProductionBatchStatus.IN_PRODUCTION,
    assignedWorkshop: 'Artisan Workshop 1 (Savar)',
    assignedTeam: 'Master Weaver Rafiq',
    startDate: '2026-09-03',
    expectedCompletion: '2026-09-14',
    actualCompletion: null,
    notes: 'Ongoing braiding on looms.',
    qcStatus: QCStatus.PENDING,
    qcInspections: [],
  },
  {
    id: 'BAT-2026-083',
    batchNumber: 'BAT-2026-083',
    orderId: null, // Stock build
    orderNumber: null,
    productId: 'prod-001',
    productTitle: 'AST Handmade Macramé Belt',
    variantId: 'var-khk-m',
    sku: 'AST-BLT-KHK-M',
    color: 'Khaki',
    size: 'M (32–35")',
    quantity: 80,
    completedQty: 80,
    status: ProductionBatchStatus.APPROVED,
    assignedWorkshop: 'Artisan Workshop 2 (Gazipur)',
    assignedTeam: 'Ustad Shafi',
    startDate: '2026-08-20',
    expectedCompletion: '2026-08-30',
    actualCompletion: '2026-08-29',
    notes: 'Replenishment for high-demand Khaki stock.',
    qcStatus: QCStatus.PASSED,
    qcInspections: [
      {
        id: 'qc-001',
        inspectionDate: '2026-08-30',
        inspector: 'Senior QC Lead Tareq',
        quantityInspected: 80,
        quantityPassed: 80,
        quantityFailed: 0,
        defects: [],
        notes: 'Flawless braid tension and buckle finish. 100% Passed.',
        passed: true,
      },
    ],
  },
  {
    id: 'BAT-2026-084',
    batchNumber: 'BAT-2026-084',
    orderId: null,
    orderNumber: null,
    productId: 'prod-001',
    productTitle: 'AST Handmade Macramé Belt',
    variantId: 'var-mrn-m',
    sku: 'AST-BLT-MRN-M',
    color: 'Maroon',
    size: 'M (32–35")',
    quantity: 50,
    completedQty: 0,
    status: ProductionBatchStatus.QUEUED,
    assignedWorkshop: 'Artisan Workshop 3 (Narayanganj)',
    assignedTeam: 'Artisan Tariq',
    startDate: '2026-09-08',
    expectedCompletion: '2026-09-20',
    actualCompletion: null,
    notes: 'Queued raw cord dyeing in progress.',
    qcStatus: QCStatus.PENDING,
    qcInspections: [],
  },
];

// ================= 9. PAYMENTS LEDGER =================
export const INITIAL_PAYMENTS = [
  {
    id: 'pay-001',
    orderId: 'ord-whl-001',
    orderNumber: 'ORD-WHL-2026-001',
    companyName: 'Atelier Artisan S.A.',
    customerName: 'Camille Laurent',
    amount: 136300,
    paymentType: 'Deposit (50%)',
    paymentMethod: 'Bank Wire Transfer',
    transactionRef: 'WIRE-CITY-8491029',
    status: PaymentStatus.PAID,
    date: '2026-09-01',
    notes: '50% Production Advance via SWIFT wire.',
  },
  {
    id: 'pay-002',
    orderId: 'sam-001',
    orderNumber: 'SAM-2026-001',
    companyName: 'Atelier Artisan S.A.',
    customerName: 'Camille Laurent',
    amount: 4900,
    paymentType: 'Sample Fee',
    paymentMethod: 'Credit Card / Stripe',
    transactionRef: 'STRIPE-CH-992810',
    status: PaymentStatus.PAID,
    date: '2026-08-12',
    notes: 'Paid sample development fee.',
  },
  {
    id: 'pay-003',
    orderId: 'sam-002',
    orderNumber: 'SAM-2026-002',
    companyName: 'Nordic Bohemian Living Ltd',
    customerName: 'Freja Lindegaard',
    amount: 4400,
    paymentType: 'Sample Fee',
    paymentMethod: 'Bank Wire Transfer',
    transactionRef: 'DK-WIRE-11029',
    status: PaymentStatus.PAID,
    date: '2026-08-26',
    notes: 'Paid sample development fee.',
  },
  {
    id: 'pay-004',
    orderId: 'sam-003',
    orderNumber: 'SAM-2026-003',
    companyName: 'Sonoma Coast Apparel Co.',
    customerName: 'Marcus Vance',
    amount: 3900,
    paymentType: 'Sample Fee',
    paymentMethod: 'Credit Card / Stripe',
    transactionRef: 'STRIPE-CH-774910',
    status: PaymentStatus.PAID,
    date: '2026-08-30',
    notes: 'Paid sample fee.',
  },
];

// ================= 10. SHIPMENTS & LOGISTICS =================
export const INITIAL_SHIPMENTS = [
  {
    id: 'shp-001',
    orderId: 'ord-ret-002',
    orderNumber: 'ORD-RET-2026-8815',
    customerName: 'Nusrat Jahan',
    companyName: null,
    destination: 'Amanat Tower, 4th Floor, Nasirabad, Chittagong, Bangladesh',
    city: 'Chittagong',
    carrier: 'Steadfast Courier',
    trackingNumber: 'ST-99820194BD',
    shippingCost: 100,
    shippingDate: '2026-09-05',
    deliveryDate: '2026-09-08',
    status: ShipmentStatus.SHIPPED,
    itemsSummary: '1x Macramé Belt (Brown, M)',
    notes: 'Standard D2C COD delivery.',
  },
  {
    id: 'shp-002',
    orderId: 'sam-001',
    orderNumber: 'SAM-2026-001',
    customerName: 'Camille Laurent',
    companyName: 'Atelier Artisan S.A.',
    destination: '14 Rue du Faubourg Saint-Honoré, 75008 Paris, France',
    city: 'Paris',
    carrier: 'DHL Express',
    trackingNumber: 'DHL-EX-88291039',
    shippingCost: 2500,
    shippingDate: '2026-08-14',
    deliveryDate: '2026-08-18',
    status: ShipmentStatus.DELIVERED,
    itemsSummary: '2x Sample Belts (Black, Brown)',
    notes: 'International courier package delivered.',
  },
  {
    id: 'shp-003',
    orderId: 'sam-002',
    orderNumber: 'SAM-2026-002',
    customerName: 'Freja Lindegaard',
    companyName: 'Nordic Bohemian Living Ltd',
    destination: 'Vesterbrogade 48, 1620 København, Denmark',
    city: 'Copenhagen',
    carrier: 'FedEx Priority',
    trackingNumber: 'FEDEX-IN-9920194',
    shippingCost: 2000,
    shippingDate: '2026-08-28',
    deliveryDate: '2026-09-01',
    status: ShipmentStatus.DELIVERED,
    itemsSummary: '2x Sample Belts (Khaki, Navy)',
    notes: 'Delivered in Copenhagen.',
  },
];

// ================= 11. OPERATIONAL EXPENSES =================
export const INITIAL_EXPENSES = [
  {
    id: 'exp-001',
    category: 'Raw Materials (Cotton Cord & Buckles)',
    description: 'Bulk order of 4.5mm Organic Cotton Cords (5000m) & 400x Brushed Alloy Buckles',
    amount: 100000,
    date: '2026-08-25',
    paymentRef: 'PO-RAW-8819',
  },
  {
    id: 'exp-002',
    category: 'Artisan Weaving Wages',
    description: 'Bi-weekly artisan piece-rate disbursement (Savar & Gazipur Workshops)',
    amount: 48000,
    date: '2026-08-31',
    paymentRef: 'PAYROLL-AUG-B',
  },
  {
    id: 'exp-003',
    category: 'Freight & Logistics',
    description: 'DHL & FedEx International Courier shipments for B2B samples',
    amount: 6000,
    date: '2026-09-02',
    paymentRef: 'INV-DHL-9941',
  },
];

// ================= 12. INTERNAL NOTIFICATIONS =================
export const INITIAL_NOTIFICATIONS = [
  {
    id: 'notif-001',
    type: NotificationType.LOW_STOCK,
    title: 'Low Stock Alert: Maroon [M]',
    message: 'Available stock is at 12 units (Safety threshold: 15 units).',
    timestamp: '2026-09-07 09:30',
    isRead: false,
    targetModule: 'inventory',
    targetId: 'var-mrn-m',
  },
  {
    id: 'notif-002',
    type: NotificationType.PRODUCTION_COMPLETED,
    title: 'Batch Ready for QC Inspection',
    message: 'Batch BAT-2026-081 (100x Black M) completed weaving at Savar Workshop.',
    timestamp: '2026-09-06 17:15',
    isRead: false,
    targetModule: 'production',
    targetId: 'BAT-2026-081',
  },
  {
    id: 'notif-003',
    type: NotificationType.PAYMENT_RECEIVED,
    title: '50% B2B Deposit Received (৳136,300)',
    message: 'Atelier Artisan S.A. wire transfer verified for ORD-WHL-2026-001.',
    timestamp: '2026-09-01 14:05',
    isRead: true,
    targetModule: 'finance',
    targetId: 'ord-whl-001',
  },
  {
    id: 'notif-004',
    type: NotificationType.LEAD_NEW,
    title: 'New Wholesale Lead: Sonoma Coast',
    message: 'Marcus Vance from Sonoma Coast Apparel Co. (500 pcs estimated).',
    timestamp: '2026-08-20 11:00',
    isRead: true,
    targetModule: 'wholesale',
    targetId: 'lead-001',
  },
];

// ================= 13. AUDIT ACTIVITY LOGS =================
export const INITIAL_ACTIVITY_LOGS = [
  {
    id: 'act-001',
    actor: 'Admin Operations',
    action: ActivityActionType.BATCH_STATUS_CHANGED,
    entityType: 'Production Batch',
    entityId: 'BAT-2026-081',
    details: 'Status changed from In Production → Quality Control',
    timestamp: '2026-09-06 17:15',
  },
  {
    id: 'act-002',
    actor: 'Admin Operations',
    action: ActivityActionType.STOCK_ADJUSTED,
    entityType: 'Inventory',
    entityId: 'AST-BLT-BLK-M',
    details: 'Stock adjusted: +20 units (Reason: Production delivery Savar)',
    timestamp: '2026-09-06 16:00',
  },
  {
    id: 'act-003',
    actor: 'Admin Operations',
    action: ActivityActionType.ORDER_STATUS_CHANGED,
    entityType: 'Order',
    entityId: 'ORD-RET-2026-8812',
    details: 'Status changed from New → Confirmed. Inventory reserved.',
    timestamp: '2026-09-06 15:00',
  },
  {
    id: 'act-004',
    actor: 'Shipping Lead',
    action: ActivityActionType.SHIPMENT_DISPATCHED,
    entityType: 'Shipment',
    entityId: 'ST-99820194BD',
    details: 'Dispatched with Steadfast Courier to Nusrat Jahan (Chittagong)',
    timestamp: '2026-09-05 16:30',
  },
  {
    id: 'act-005',
    actor: 'System Engine',
    action: ActivityActionType.QUOTE_CONVERTED,
    entityType: 'Quotation',
    entityId: 'QTE-2026-001',
    details: 'Converted to Wholesale Order ORD-WHL-2026-001. Sample credit ৳2,400 applied.',
    timestamp: '2026-09-01 10:15',
  },
];

// ================= 14. INVENTORY MOVEMENT AUDIT =================
export const INITIAL_INVENTORY_MOVEMENTS = [
  {
    id: 'mov-001',
    timestamp: '2026-09-01 10:20',
    variantId: 'var-blk-m',
    sku: 'AST-BLT-BLK-M',
    type: InventoryMovementType.RESERVATION,
    quantity: -15,
    referenceId: 'ORD-WHL-2026-001',
    reason: 'Reserved for Wholesale Bulk Order Atelier Artisan',
    balanceOnHand: 65,
    balanceAvailable: 50,
    performedBy: 'System Engine',
  },
  {
    id: 'mov-002',
    timestamp: '2026-09-06 15:00',
    variantId: 'var-blk-m',
    sku: 'AST-BLT-BLK-M',
    type: InventoryMovementType.RESERVATION,
    quantity: -1,
    referenceId: 'ORD-RET-2026-8812',
    reason: 'Reserved for Retail COD Order Tanvir Hossain',
    balanceOnHand: 65,
    balanceAvailable: 49,
    performedBy: 'Admin',
  },
  {
    id: 'mov-003',
    timestamp: '2026-09-05 16:30',
    variantId: 'var-brn-m',
    sku: 'AST-BLT-BRN-M',
    type: InventoryMovementType.OUTBOUND,
    quantity: -1,
    referenceId: 'ORD-RET-2026-8815',
    reason: 'Stock deducted on shipment dispatch (Steadfast)',
    balanceOnHand: 39,
    balanceAvailable: 30,
    performedBy: 'Shipping Lead',
  },
];
